version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://cosmic_user:cosmic_password@db/cosmic_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cosmic_user
      - POSTGRES_PASSWORD=cosmic_password
      - POSTGRES_DB=cosmic_db

volumes:
  postgres_data: